[phases.setup]
commands = ["cd BackEnd", "curl -sL https://deb.nodesource.com/setup_20.x | bash -", "apt-get install -y nodejs"]

[phases.build]
commands = ["npm install", "npm run build"]

[phases.deploy]
commands = ["npm start"]
